export const GET_NAVBAR_SETTINGS = "GET_NAVBAR_SETTINGS"
export const SET_ERROR = "SET_ERROR"
export const GET_HOMEPAGE_SECTIONONE = "GET_HOMEPAGE_SECTIONONE"
export const GET_HEADER_CONTACTS = "GET_HEADER_CONTACTS"
export const GET_HOMEPAGE_PRODWLTXT_ONE = "GET_HOMEPAGE_PRODWLTXT_ONE"
export const GET_HOMEPAGE_PRODWLTXT_TWO = "GET_HOMEPAGE_PRODWLTXT_TWO"

