export const GET_PRODUCTS = 'GET_PRODUCTS'; 
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_ERROR= 'SET_ERROR';
export const SWITCH_TO_FAVOURITE = 'SWITCH_TO_FAVOURITE';
export const GET_FAVOURITES_PRODUCTS = 'GET_FAVOURITES_PRODUCTS';
export const SET_FAVOURITES_PRODUCTS = 'SET_FAVOURITES_PRODUCTS';